<a href="https://colab.research.google.com/github/Shivaram17/100DaysOfPythonCoding/blob/main/10078numpyreShape.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# # web scraping for - Opening several Google search results.
# import requests
# import bs4, webbrowser, sys

# print("Googling....")#display google while retrieving google search bar
# res = requests.get('https://www.google.com/search?q=' + ' '.join(sys.argv[1:]))
# res.raise_for_status()
# #TODO Retrieve top search result links
# soup = bs4.BeautifulSoup(res.text, features="html.parser")

# #TODO open a browser tab for each result
# linkElems = soup.select('.r a')
# numOpen = min(5, len(linkElems))
# for i in range(numOpen):
#   webbrowser.open('http//google.com' + linkElems[i].get('href'))

In [3]:
import numpy as np
x = np.array([1,2,45,6,7,1,23,4,67,9,12,32])
x = x.reshape(4,3)
print(x)

[[ 1  2 45]
 [ 6  7  1]
 [23  4 67]
 [ 9 12 32]]
