<a href="https://colab.research.google.com/github/Shivaram17/100DaysOfPythonCoding/blob/main/10086numpyRandomModules.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
#numpy array for random module
from numpy import random
#random from 0 to 5
x = random.randint(5)
#random 2d array of float 
y = random.rand(3,4)
# random choice for arrays
z = random.choice([2,3,43,323,5], size = (3,5))
print(z)


[[  2   5   2   3 323]
 [  2   3 323   3  43]
 [ 43   5 323   5   5]]
