<a href="https://colab.research.google.com/github/Shivaram17/100DaysOfPythonCoding/blob/main/10087numpyRandomDistribution%26Permutation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
#numpy array for random module for data distribution
import numpy as np
from numpy import random
# random choice for arrays
z = random.choice([1,3,5,7,9], p = [0.1,0.1,0.3,0.1,0.4], size = (3,5))
arr = np.array([1,3,5,6,8,9])
#random shuffle
random.shuffle(arr)
#random permutation
print(random.permutation(arr))
print(z)
print(arr)


[3 9 1 5 8 6]
[[5 9 5 5 5]
 [5 3 5 9 3]
 [9 9 5 9 1]]
[5 8 1 9 3 6]
